In [13]:
#libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [2]:
dataset = pd.read_csv('IRIS.csv')
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

In [11]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
dataset.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [18]:
#spliting data into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [19]:
#since Y is categorical
#labeling first
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
Label = LabelEncoder()
Y_train = Label.fit_transform(Y_train)
Y_test = Label.transform(Y_test)

In [21]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [27]:
y_predict = nb.predict(X_test)

In [28]:
y_predict

array([0, 2, 1, 1, 2, 1, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 1, 1, 2, 1, 1, 2,
       0, 0, 0, 1, 2, 0, 0, 2])

In [29]:
Y_test

array([0, 1, 1, 1, 2, 1, 1, 0, 0, 1, 0, 1, 2, 0, 0, 2, 1, 1, 2, 1, 1, 2,
       0, 0, 0, 1, 2, 0, 0, 2])

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test,y_predict)
cm

array([[11,  0,  0],
       [ 0, 10,  2],
       [ 0,  0,  7]], dtype=int64)

In [38]:
accuracy_score(Y_test,y_predict)

0.9333333333333333